### PR TITLE
fix optee-os compatible for s4sk

### PR DESCRIPTION
**Pull request by rshym**
This PR is created just to merge the patch provided in the issue https://github.com/xen-troops/meta-xt-prod-devel-rcar-gen4/issues/97

### CODE REVIEW

**Review by lorc — COMMENTED** [review]
Could we please have more elaborate commit message? 

I hope @mdege will not mind if you write something like

```
s4sk: add optee compatibility string

Provide OP-TEE machine name "rcar-s4sk_s4" for the S4SK board

Signed-of...
```

**Comment by mdege** [comment]
Yes, that is fine with me.

**Comment by rshym** [comment]
The commit message is updated.

**Review by lorc — APPROVED** [review]
`Acked-by: Volodymyr Babchuk <volodymyr_bachuk@epam.com>`

**Comment by rshym** [comment]
`Ack` is added. Ready to be merged.

**Pull request merged**
