### PR TITLE
yaml: move common_data inside the build directory

### PR DESCRIPTION
**Pull request by rshym**
All common data should be kept inside the build folder.

### CODE REVIEW

**Comment by Deedone** [comment]
I strongly disagree with the statement that it is better to build with separate caches. As we frequently build multiple images that are very similar to each other, removing the shared cache can worsen build times a lot without giving any clear benefit. I propose to keep it but place it at a new location similar to how downloads dir is moved.

**Comment by rshym** [comment]
> I strongly disagree with the statement that it is better to build with separate caches.

After reading related discussions I now agree with your point regarding state caches.
So, this PR now moves `common_data` inside the build directory, so all build-related stuff is created in the place, that is expected by the user.

**Comment by Deedone** [comment]
Nice `Acked-by: Mykyta Poturai <mykyta_poturai@epam.com>`

**Comment by rshym** [comment]
`Ack` is added.
Ready to be merged.

**Pull request merged**
