### PR TITLE
Add support for S4SK

### PR DESCRIPTION
**Pull request by rshym**
New files are added from the branch `s4sk-1.2.1` of renesas-rcar/meta-xt-prod-devel-rcar-gen4.

### CODE REVIEW

**Comment by rshym** [comment]
Rebased and split for two PRs (this one and https://github.com/xen-troops/meta-xt-rcar/pull/48).

**Comment by rshym** [comment]
Built (with https://github.com/xen-troops/meta-xt-rcar/pull/48) for spider and s4sk.
Tested on the Spider board only.

**Comment by lorc** [comment]
Regarding "domd: linux: add s4sk-related files",  "domu: linux: add s4sk-related device tree" and "control-domain: add s4sk-specific guest configs ": I believe most of the files touched here are shared between the boards. For example large portions of the device trees are the same. AFAIK, only difference may be in memory nodes. So it is better to move all the common parts into separate files and include them where needed.

**Comment by rshym** [comment]
Contains one (the first) commit from https://github.com/xen-troops/meta-xt-prod-devel-rcar-gen4/pull/82

Was successfully built for both boards - Spider and S4SK.
Smoke-tested on the Spider 1.0

**Comment by lorc** [comment]
LGTM:

`Acked-by: Volodymyr Babchuk <volodymyr_babchuk@epam.com>`

Just one thing: put  "domd: domu: linux: add s4sk-related files" before "domd: domu: make recipes use board-independent naming", otherwise it makes no sense, as you are referring to a file that is still not present in the tree.

**Comment by rshym** [comment]
> Just one thing: put "domd: domu: linux: add s4sk-related files" before "domd: domu: make recipes use board-independent naming", otherwise it makes no sense, as you are referring to a file that is still not present in the tree.

I have double-checked both files mentioned in the first commit - `0002-PCIe-MSI-support.${MACHINE}.patch` and `r8a779f0-${MACHINE}-domu.dts`. As far as we do not have `s4sk` machine, we are good. The first file (.patch) is created by the commit itself, and the second (.dts) is already present in the source tree. The possibility to specify `s4sk` is introduced be the last commit, when corresponding files are in the tree.
Also, I have successfully built the product, removing the three last commits, to make sure, that the source tree is valid after "domd: domu: make recipes use board-independent naming".

So, I'm adding `Ack`, after this checks.

**Comment by rshym** [comment]
`Ack` was added.
Smoke-tested on the Spider 1.0.
Ready to be merged with https://github.com/xen-troops/meta-xt-rcar/pull/48

**Pull request merged**
