### PR TITLE
Fix branch for xt-common and update DomD's Linux

### PR DESCRIPTION
**Pull request by rshym**
- yaml: use dunfell branch for meta-xt-common
- domd: Update version of linux

Have to be merged with https://github.com/xen-troops/meta-xt-prod-devel-rcar-gen4/pull/63

### CODE REVIEW

**Comment by rshym** [comment]
This PR (with #63) was tested on the Spider board.
Dom0 and DomD start OK, but the network bridge is not starting due to some timeout.
The proposal is to merge this PR and #63, and than to fix the bridge.

**Comment by lorc** [comment]
`Acked-by: Volodymyr Babchuk <volodymyr_babchuk@epam.com>`

**Comment by LKomaryanskiy** [comment]
`Acked-by: Leonid Komarianskyi <leonid_komarianskyi@epam.com>`

**Comment by rshym** [comment]
Both `Ack`'s are added.

**Pull request merged**
