### PR TITLE
Rename yaml with the product configuration

### PR DESCRIPTION
**Pull request by rshym**
Rename prod-devel-rcar-s4.yaml to prod-devel-rcar4.yaml as we are going to add support for other gen4 SOCs not only S4. And the current name may be missleading for users.

### CODE REVIEW

**Review by lorc — APPROVED** [review]
`Acked-by: Volodymyr Babchuk <volodymyr_babchuk@epam.com>`

**Comment by rshym** [comment]
`Ack` is added.
No testing is required.
Ready to be merged.

**Comment by lorc** [comment]
Could you please resolve merge conflicts?

**Comment by rshym** [comment]
That conflict seems like an issue on the GitHub side, because on my local PC the patch rebased smoothly.
Anyway, I repushed PR, and now GitHub is happy.

**Pull request merged**
