### PR TITLE
domd: update Snort to latest 2.9.20 version

### PR DESCRIPTION
**Pull request by LKomaryanskiy**

### CODE REVIEW

**Review by firscity — APPROVED** [review]
`Reviewed-by: Dmytro Firsov <dmytro_firsov@epam.com>`

**Comment by lorc** [comment]
Would you please add at least one paragraph to the commit description?

**Comment by LKomaryanskiy** [comment]
@lorc Thank you for your review. I have added a description with the main reasons why we should update Snort to the latest version.

**Comment by lorc** [comment]
`Acked-by: Volodymyr Babchuk <volodymyr_babchuk@epam.com>`

**Pull request merged**
