### PR TITLE
Update override separators and image descriptor

### PR DESCRIPTION
**Pull request by rshym**
- Replace override separator `_` with `:`
- yaml: replace `files` with `items`

### CODE REVIEW

**Comment by rshym** [comment]
Tested on the Spider board.

**Comment by rshym** [comment]
Updated `min_ver: "0.15"` as required for proper handling of `items`.

**Comment by lorc** [comment]
`Acked-by: Volodymyr Babchuk <volodymyr_babchuk@epam.com>`

**Comment by rshym** [comment]
`Ack` is added, rebased, and tested.
Ready to be merged.

**Pull request merged**
