### PR TITLE
domd: add UFS support for Spider U-Boot

### PR DESCRIPTION
**Pull request by LKomaryanskiy**
S4 board provides UFS device which can be used for booting images from it. Enabling UFS in U-Boot requires porting several drivers from Linux Kernel such as UFS driver and CPG reset driver for resetting UFS on init. Also, added appropriate configs needed for enabling these drivers.

### CODE REVIEW

**Comment by LKomaryanskiy** [comment]
UPD: added Gen4 CPG reset driver functionality needed for UFS reset.

**Comment by lorc** [comment]
Could you please expand the commit message a bit?

**Comment by LKomaryanskiy** [comment]
@lorc thank you for your review comment. I've added description to the patch and PR.

**Review by lorc — APPROVED** [review]
Thank you. Now at least we can see what to expect from this change

`Acked-by: Volodymyr Babchuk <volodymyr_babchuk@epam.com>`

**Comment by LKomaryanskiy** [comment]
UPD: Added AB tag. @lorc thank you for review.

**Comment by lorc** [comment]
@rshym, please note that we are still adding changes to `meta-xt-prod-devel-rcar-gen4`

**Pull request merged**
